/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ccsakhalazqsvluqokhi"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjc2FraGFsYXpxc3ZsdXFva2hpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NzkwNjUsImV4cCI6MjA3NDM1NTA2NX0.D6cKnDtg-aKUuxYFiKpxpWtz-gsDl1oxTrg72TeEikM"